### ISSUE TITLE
"client-side rendering" does not change to "server-side rendering" on routing

### ISSUE THREAD

**Issue by Ade-Joshe** [UnlyEd/universal-language-detector#12]
Routing does not change the screen's rendering type label in demo.

**Comment by Vadorequest** [comment]
What's the "screen's rendering type label"?

**Comment by Ade-Joshe** [comment]
It switches to client-side rendering and doesn't change on subsequent routing

**Comment by Vadorequest** [comment]
Could you please make a video and explain what's not working as expected? I tested the demo and everything seem to behave as expected.

You can use https://chrome.google.com/webstore/detail/screencastify-screen-vide/mmeijimgabbpbgpdklnllpncmdofkcpn
