### ISSUE TITLE
Is there a way to set custom cookie name to detect?

### ISSUE THREAD

**Issue by miklosz** [UnlyEd/universal-language-detector#13]

**Comment by Vadorequest** [comment]
I don't think so.

There is no built in mechanism to change the cookie's name, although the lib we use do allow for a dynamic name.

https://github.com/UnlyEd/universal-language-detector/blob/2637628bfe7e12f79a2b128bd0cca26c5b657ff3/src/index.ts#L19

https://github.com/i18next/i18next-browser-languageDetector#detector-options

**Comment by miklosz** [comment]
Thanks for quick reply. I'll try to manually overwrite it.
For a moment I thought this project is abandoned

**Comment by Vadorequest** [comment]
It's not abandoned (we still use it in production to this day), but there isn't much to be done, it works well! :)
