### ISSUE TITLE
Change language server side

### ISSUE THREAD

**Issue by denny7** [UnlyEd/universal-language-detector#3]
Hello! Is there a way to change language server side after detect it?

**Comment by Vadorequest** [comment]
Hello @denny7 , I'm not sure what you mean. Would you mind explaining your use-case? 

This plugin only detects the language, by relying on cookies. So, changing the cookie will change the language used by the server side.

Take a look at the Next.js example https://github.com/UnlyEd/universal-language-detector/tree/master/examples/with-next
